config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do #as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: :edit_user_registration
    patch 'users', to: 'devise/registrations#update', as: :user_registration
  end

  root to: 'pages#home'

  # -------- ADMIN ROUTES ---------
  authenticate :user, ->(user) { user.admin } do
    namespace :admin do
      resources :users, only: %i[index create]
      resources :documents, only: %i[new create edit update] do
        patch :validate
      end
    end
  end

  resources :documents, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  include DatetimeHelper

  LANGUAGES = %w[FR EN]

  validates :title, presence: true
  validates :language, presence: true, inclusion: { in: LANGUAGES }
  validates :attachment, presence: true

  before_save :set_format

  scope :validated, -> { where.not(validation_at: nil) }

  has_one_attached :attachment

  def validated?
    validation_at.present?
  end

  private

  def content_type
    self.attachment.blob.content_type
  end

  def main_content_type
    content_type.split("/").first
  end

  def set_format
    case main_content_type
    when "image"
      self.format = "image"
    when "video"
      self.format = "video"
    when "application"
      case content_type
      when "application/pdf"
        self.format = "pdf"
      when "application/vnd.ms-powerpoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        self.format = "ppt"
      when "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        self.format = "xls"
      when "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        self.format = "word"
      else
        self.format = "other"
      end
    else
      self.format = "other"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :password_expirable, :password_archivable

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController
  before_action :find_document, only: %i[edit update]
  before_action :find_document_with_document_id, only: %i[validate]

  def validate
    @document.validation_at = DateTime.now
    if @document.save
      redirect_to documents_path
    else
      render :show
    end
  end

  def new
    @document = Document.new
    authorize([:admin, @document])
  end

  def create
    @document = Document.new(document_params)
    authorize([:admin, @document])
    if @document.save
      redirect_to document_path(@document)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to document_path(@document)
    else
      render :edit
    end
  end

  private

  def document_params
    params.require(:document).permit(:title, :language, :usage, :attachment)
  end

  def find_document
    @document = Document.find(params[:id])
    authorize([:admin, @document])
  end

  def find_document_with_document_id
    @document = Document.find(params[:document_id])
    authorize([:admin, @document])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = policy_scope([:admin, User])
    @user = User.new
  end

  def create
    @users = policy_scope([:admin, User])
    @user = User.new(user_params)
    authorize([:admin, @user])
    if @user.save
      @user.need_change_password! # thanks to gem devise-security
      redirect_to admin_users_path
    else
      render :index
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def show
    @document = Document.find(params[:id])
    authorize @document
  end

  def index
    if current_user.admin?
      @documents = policy_scope(Document)
    else
      @documents = policy_scope(Document).validated
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime_helper.rb
module DatetimeHelper
  def display_date_for(datetime, attrs = {})
    format = attrs[:without_year] ? '%A %d %B' : '%A %d %B %Y'
    l(datetime, format: format)
  end
end

app/views/admin/documents/_form.slim
= simple_form_for [:admin, @document], remote: true do |f|
  = f.input :title
  = f.input :language, as: :radio_buttons, collection: Document::LANGUAGES
  = f.input :usage
  = f.input :attachment, as: :file
  = f.submit

app/views/admin/documents/edit.html.erb
<div class="container">
  <%= render 'form', document: @document %>
</div>

app/views/admin/documents/new.html.erb
<div class="container">
  <%= render 'form', document: @document %>
</div>

app/views/admin/users/_form.html.erb
<%= simple_form_for user, url: admin_users_path, method: :post, html: { class: "table-users-inputs" }, remote: true do |f| %>
  <%= f.input :first_name, label: false, wrapper_html: { class: "table-users-new-line" } %>
  <%= f.input :last_name, label: false %>
  <%= f.input :email, label: false %>
  <%= f.input :password, label: false %>
  <!-- Replace <%#= f.submit %> to allow using font-awesome icon -->
  <button type="submit"><i class="fa fa-check"></i></button>
<% end %>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="table table-users">
    <div class="table-users-new-line">Prénom</div>
    <div>Nom</div>
    <div>E-mail</div>
    <div>Mot de passe</div>

    <% @users.each do |user| %>
      <div class="table-users-new-line"><%= user.first_name %></div>
      <div><%= user.last_name %></div>
      <div><%= user.email %></div>
    <% end %>

    <%= render 'form', user: @user %>
  </div>
</div>

app/views/documents/_card.slim
.card
  - case document.format
    - when "image"
      = image_tag document.attachment
    - when "video"
      = video_tag (url_for(document.attachment) + "#t=0.5")
    - when "pdf"
      i.d-flex-default.far.fa-file-pdf style="color: red"
    - when "xls"
      i.d-flex-default.far.fa-file-excel style="color: green"
    - when "ppt"
      i.d-flex-default.far.fa-file-powerpoint style="color: red"
    - when "word"
      i.d-flex-default.far.fa-file-word style="color: blue"
    - else
      img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg"
  .card-content.d-flex-column-between
    .card-infos
      p.cut-text = document.title
      p.cut-text = document.language
      - if document.validated?
        p.cut-text = display_date_for(document.validation_at)
      - else
        p.cut-text Non validé
    .card-actions
      = link_to document_path(document) do
        i.btn.fa.fa-search

app/views/documents/index.slim
.container
  .cards
    - if current_user.admin?
      .card.d-flex.justify-content-center.align-items-center
        = link_to "+", new_admin_document_path, style: "font-size: 6rem"
    - @documents.each do |document|
      = render 'card', document: document

app/views/documents/show.slim
.container
  p.mb-0 Titre:
  p = @document.title
  p.mb-0 Langue:
  p = @document.language
  p.mb-0 Droits d'utilisation:
  p = simple_format(@document.usage)

  div
    - if policy([:admin, @document]).validate?
      = link_to 'Mettre en ligne', admin_document_validate_path(@document), method: :patch, class: "btn"
    - if policy([:admin, @document]).edit?
      = link_to 'Modifier', edit_admin_document_path(@document), class: "btn"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GileadMediatheque</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if current_user.present? %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%#= link_to root_path, class: "navbar-brand" do %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.gilead.com/-/media/gilead-corporate/images/global/logo-gilead-create-possible.png", style: "height: 40px; width: auto" %>
      <% end %>

    <div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Documents", documents_path, class: "nav-link" %>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Utilisateurs", admin_users_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Mon compte", edit_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>

  <% end %>